// Generated by CoffeeScript 1.6.2
/*
  tbaldw.in
  
  Music by Jon Hopkins (http://www.jonhopkins.co.uk) - Small Memory, Tunng Remix

  This documentation is helpful for the audio stuff:
  https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html

  Also: thanks to Justin Windle (soulwire.co.uk)
  This experiment was inspired by and built while referencing
  his codepen: http://codepen.io/soulwire/pen/Dscga
*/


(function() {
  var Bar, VIZ,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  VIZ = (function() {
    function VIZ(el, audio, smoothing, fft) {
      var src, warning,
        _this = this;

      this.el = el != null ? el : document.body;
      this.audio = audio != null ? audio : new Audio();
      this.smoothing = smoothing != null ? smoothing : 0.8;
      this.fft = fft != null ? fft : 2048;
      this.resizeWindow = __bind(this.resizeWindow, this);
      this.onMouseMove = __bind(this.onMouseMove, this);
      this.animate = __bind(this.animate, this);
      this.render = __bind(this.render, this);
      this.mouse = {
        x: 0,
        y: 0
      };
      this.AudioContext = self.AudioContext || self.webkitAudioContext;
      this.enabled = this.AudioContext != null;
      if (/Safari/.test(navigator.userAgent) && !/Chrome/.test(navigator.userAgent)) {
        return;
      }
      if (typeof this.audio === 'string') {
        src = this.audio;
        this.audio = new Audio();
        this.audio.controls = true;
        this.audio.src = src;
      }
      this.context = new this.AudioContext();
      this.jsNode = this.context.createJavaScriptNode(this.fft);
      this.analyser = this.context.createAnalyser();
      this.analyser.smoothingTimeConstant = this.smoothing;
      this.analyser.fftSize = this.fft;
      this.data = {
        bands: new Uint8Array(this.analyser.frequencyBinCount),
        waveform: new Uint8Array(this.analyser.frequencyBinCount)
      };
      this.audio.addEventListener('canplay', function() {
        _this.el.appendChild(_this.audio);
        _this.source = _this.context.createMediaElementSource(_this.audio);
        _this.source.connect(_this.analyser);
        _this.analyser.connect(_this.jsNode);
        _this.jsNode.connect(_this.context.destination);
        _this.source.connect(_this.context.destination);
        _this.audio.play();
        document.addEventListener("keyup", function(e) {
          if (e.which === 32) {
            if (_this.audio.paused) {
              return _this.audio.play();
            } else {
              return _this.audio.pause();
            }
          }
        });
        return _this.jsNode.onaudioprocess = function() {
          _this.analyser.getByteFrequencyData(_this.data.bands);
          _this.analyser.getByteTimeDomainData(_this.data.waveform);
          return typeof _this.onUpdate === "function" ? _this.onUpdate() : void 0;
        };
      });
      warning = document.getElementById('warning');
      if (this.enabled) {
        warning.style.display = "none";
      }
      this.setup3D();
    }

    VIZ.prototype.setup3D = function() {
      var aspect, bar, geometry, height, i, material, opts, width, x, z, _i, _j, _ref, _ref1;

      width = this.el.offsetWidth;
      height = window.innerHeight;
      aspect = width / height;
      this.dim = {
        width: width,
        height: height,
        aspect: aspect
      };
      this.renderer = new THREE.WebGLRenderer({
        antialias: true
      });
      this.renderer.setSize(this.dim.width, this.dim.height);
      this.el.appendChild(this.renderer.domElement);
      this.scene = new THREE.Scene();
      this.camera = new THREE.PerspectiveCamera(45, this.dim.aspect, 1, 4000);
      this.camPos = {
        x: 0,
        y: 0,
        z: 150
      };
      this.scene.add(this.camera);
      this.camera.position.set(this.camPos.x, this.camPos.y, this.camPos.z);
      this.light = new THREE.DirectionalLight(0xffffff, .9);
      this.light.position.set(400, 1000, 1000);
      this.scene.add(this.light);
      this.bars = [];
      geometry = new THREE.SphereGeometry(1);
      for (i = _i = 0, _ref = this.analyser.frequencyBinCount - 50; _i < _ref; i = _i += 1) {
        x = i * 0.7;
        if (i % 2 === 0) {
          x = -x;
        }
        material = new THREE.MeshPhongMaterial({
          color: 0x69D2E7
        });
        opts = {
          material: material,
          geometry: geometry,
          id: i,
          x: x,
          y: 0,
          z: 0
        };
        bar = new Bar(opts);
        this.scene.add(bar.shape);
        this.bars.push(bar);
      }
      for (i = _j = 0, _ref1 = this.analyser.frequencyBinCount - 50; _j < _ref1; i = _j += 1) {
        z = i * 0.7;
        if (i % 2 === 0) {
          z = -z;
        }
        material = new THREE.MeshPhongMaterial({
          color: 0x69D2E7
        });
        opts = {
          material: material,
          geometry: geometry,
          id: i,
          x: 0,
          y: 0,
          z: z
        };
        bar = new Bar(opts);
        this.scene.add(bar.shape);
        this.bars.push(bar);
      }
      this.animate();
      window.onresize = this.resizeWindow;
      return document.addEventListener("mousemove", this.onMouseMove);
    };

    VIZ.prototype.render = function() {
      var bar, _i, _len, _ref;

      _ref = this.bars;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        bar = _ref[_i];
        bar.render(this);
      }
      this.camera.position.x += (this.mouse.x / 3 - this.camera.position.x) * 0.03;
      this.camera.position.y += (-this.mouse.y / 3 - this.camera.position.y) * 0.03;
      this.camera.position.z = (abs(this.mouse.x / 10)) + 120;
      this.camera.lookAt(this.scene.position);
      return this.renderer.render(this.scene, this.camera);
    };

    VIZ.prototype.animate = function() {
      requestAnimationFrame(this.animate);
      return this.render();
    };

    VIZ.prototype.onMouseMove = function(e) {
      return this.mouse = {
        x: e.clientX - this.dim.width / 2,
        y: e.clientY - this.dim.height / 2
      };
    };

    VIZ.prototype.resizeWindow = function() {
      this.dim.width = this.el.offsetWidth;
      this.dim.height = window.innerHeight;
      this.dim.aspect = this.dim.width / this.dim.height;
      this.renderer.setSize(this.dim.width, this.dim.height);
      return this.camera.aspect = this.dim.aspect;
    };

    return VIZ;

  })();

  Bar = (function() {
    function Bar(opts) {
      this.id = opts.id;
      this.position = {};
      this.position.x = opts.x || 0;
      this.position.y = opts.y || 0;
      this.position.z = opts.z || 0;
      this.shape = new THREE.Mesh(opts.geometry, opts.material);
      this.shape.position.x = this.position.x;
      this.shape.position.y = this.position.y;
      this.shape.position.z = this.position.z;
      this.shape.rotation.x = PI / 5;
      this.shape.rotation.y = PI / 5;
    }

    Bar.prototype.render = function(ctx) {
      var data;

      data = ctx.data;
      this.position.y = max(this.position.y * 0.8, data.bands[this.id] / 5);
      return this.shape.position.y = this.position.y;
    };

    return Bar;

  })();

  window.VIZ = VIZ;

}).call(this);
